all: 
	g++ main.cpp ./TimeBankSystem.cpp ./models/user/Admin.cpp ./models/user/User.cpp ./utils/myUtils.cpp ./models/user/RegularMember.cpp ./models/skill/Skill.cpp ./models/skill/Review.cpp ./utils/time/DateTime.cpp ./utils/file/FileHandler.cpp ./utils/time/Period.cpp ./models/skill/SkillListing.cpp ./models/skill/Request.cpp
	./a.exe